name: Check System Configuration

on:
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  check-system:
    name: Check System Configuration
    runs-on: ubuntu-latest # Use a GitHub-hosted Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Display System Configuration
        run: |
          echo "### SYSTEM INFORMATION ###"
          echo "Operating System: $(uname -a)"
          echo "CPU Info:"
          lscpu
          echo "Memory Info:"
          free -h
          echo "Disk Usage:"
          df -h
          echo "Environment Variables:"
          env

      - name: Display Available Storage
        run: |
          echo "### STORAGE INFORMATION ###"
          df -h | grep '^/dev'
