name: Check System Configuration (Windows)

on:
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  check-system:
    name: Check System Configuration
    runs-on: windows-latest # Use a GitHub-hosted Windows runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Display System Configuration
        shell: cmd
        run: |
          echo ### SYSTEM INFORMATION ###
          echo Operating System: %OS%
          echo Computer Name: %COMPUTERNAME%
          echo Processor: %PROCESSOR_IDENTIFIER%
          echo Number of Processors: %NUMBER_OF_PROCESSORS%
          echo Architecture: %PROCESSOR_ARCHITECTURE%
          echo Memory Info:
          systeminfo | findstr /C:"Total Physical Memory" /C:"Available Physical Memory"
          echo Disk Usage:
          wmic logicaldisk get size,freespace,caption
          echo Environment Variables:
          set

      - name: Display Available Storage
        shell: cmd
        run: |
          echo ### STORAGE INFORMATION ###
          wmic logicaldisk where drivetype=3 get caption,freespace,size
