name: Build OpenSSL Static on Windows

on:
  workflow_dispatch:  # Memungkinkan build manual dari GitHub Actions

jobs:
  build-openssl:
    runs-on: windows-latest

    steps:
      - name: Download OpenSSL 3.x
        shell: msys2 {0}
        run: |
          git clone --depth=1 https://github.com/openssl/openssl.git
          cd openssl
          
          # Coba checkout ke tag atau branch yang benar
          if git checkout tags/openssl-3.0.0 || git checkout tags/openssl-3.1.0; then
            echo "Berhasil checkout OpenSSL"
          else
            echo "Checkout gagal, coba lagi dengan tag atau branch yang valid"
            exit 1
          fi
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            git base-devel
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            mingw-w64-x86_64-perl
            mingw-w64-x86_64-nasm

      - name: Build OpenSSL Static
        shell: msys2 {0}
        run: |
          cd openssl
          perl Configure mingw64 no-shared no-zlib --prefix=$PWD/install
          make -j$(nproc)
          make install_sw  # Pada OpenSSL 3.x, gunakan "install_sw"

      - name: Archive OpenSSL Build Artifacts
        run: |
          tar -czvf openssl-windows-static.tar.gz -C openssl/install .

      - name: Upload OpenSSL Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenSSL-Static-Windows
          path: openssl-windows-static.tar.gz
          compression-level: 0  # Gunakan 0 agar lebih cepat diunggah
