name: Get and Build OpenSSL

on:
  workflow_dispatch:

jobs:
  get-openssl:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: git

      - name: Clone OpenSSL repository
        shell: msys2 {0}
        run: |
          git clone https://github.com/openssl/openssl.git
          cd openssl

      - name: Fetch all tags from OpenSSL repository
        shell: msys2 {0}
        run: |
          cd openssl
          git fetch --tags

      - name: Checkout OpenSSL tag (3.4.0 or 3.1.0)
        shell: msys2 {0}
        run: |
          cd openssl
          if git checkout openssl-3.4.0 || git checkout openssl-3.1.0; then
            echo "Berhasil checkout OpenSSL"
          else
            echo "Checkout gagal, coba lagi dengan tag yang valid"
            exit 1
          fi

      - name: Verify OpenSSL version
        shell: msys2 {0}
        run: |
          cd openssl
          git describe --tags

      - name: Build OpenSSL
        shell: msys2 {0}
        run: |
          cd openssl
          ./Configure
          make

      - name: Create artifacts directory
        shell: msys2 {0}
        run: |
          mkdir -p openssl-artifacts

      - name: Copy built files to artifacts directory
        shell: msys2 {0}
        run: |
          cd openssl
          cp -r include ../openssl-artifacts/
          cp -r lib ../openssl-artifacts/
          cp -r apps/openssl ../openssl-artifacts/

      - name: Archive artifacts
        shell: msys2 {0}
        run: |
          tar -czvf openssl-artifacts.tar.gz -C openssl-artifacts .

      - name: Upload OpenSSL artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openssl-artifacts
          path: openssl-artifacts.tar.gz
