name: Cache OpenSSL

on:
  workflow_dispatch:  # Trigger manually from GitHub UI

jobs:
  cache-openssl:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          choco install wget

      - name: Cache OpenSSL
        uses: actions/cache@v3
        with:
          path: openssl-1.1.1l.tar.gz
          key: openssl-1.1.1l
          restore-keys: |
            openssl-1.1.1l

      - name: Download OpenSSL source
        if: steps.cache-openssl.outputs.cache-hit != 'true'
        run: |
          wget https://www.openssl.org/source/openssl-1.1.1l.tar.gz
