name: Cache Qt Source

on:
  workflow_dispatch:  # Trigger manually from GitHub UI

jobs:
  cache-qt-source:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          choco install wget
          choco install 7zip
          choco install python
          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"

      - name: Cache Qt 5.15.16 source
        id: cache-qt
        uses: actions/cache@v3
        with:
          path: qt-everywhere-opensource-src-5.15.16
          key: qt-5.15.16-${{ runner.os }}
          restore-keys: |
            qt-5.15.16

      - name: Download Qt 5.15.16 source
        if: steps.cache-qt.outputs.cache-hit != 'true'
        run: |
          wget https://ftp.jaist.ac.jp/pub/qtproject/archive/qt/5.15/5.15.16/single/qt-everywhere-opensource-src-5.15.16.tar.xz
          echo "2a25d4e90abd05284bf5bb01365c9b44  qt-everywhere-opensource-src-5.15.16.tar.xz" > qt-everywhere-opensource-src-5.15.16.tar.xz.md5
          certutil -hashfile qt-everywhere-opensource-src-5.15.16.tar.xz MD5 | findstr /i "2a25d4e90abd05284bf5bb01365c9b44"
          if ($LASTEXITCODE -ne 0) { exit 1 }

      - name: Extract Qt source with 7-Zip
        run: |
          7z e qt-everywhere-opensource-src-5.15.16.tar.xz
          7z x qt-everywhere-opensource-src-5.15.16.tar
